language: python
python:
  - "3.6"
install:
  - pip install nosexcover
  - python setup.py install
script:
  - python setup.py nosetests --with-xcoverage --cover-package=evmdasm --cover-html --cover-branch --xcoverage-file=cobertura.xml
